<?php

/*

Simple script to parse a directory of csv files.
The csv files were generated by ArcMap.  The script
goes through the directory file by file, extracts 
the last column and generates sql insert statements
which are piped into route_dist_lookuptable_insert.sql
from the command line:  php csv_parse.php > name

*/


if ($handle = opendir('./csv')) {
	while (false !== ($entry = readdir($handle))) {
		if ($entry != "." && $entry != "..") {
			$routenum = str_replace("Route", "", $entry);	
			$routenum = str_replace(".csv", "", $routenum);	
			get_districts($entry, $routenum);
		}
	}
	closedir($handle);
}



function get_districts($entry, $route){
	$dis_house = array();
	$dis_city = array();
	$dis_cong  = array();
	$dis_senate = array();

	$row = 0;
	$fname = "./csv/".$entry;

	if (($handle = fopen($fname, "r")) !== FALSE) {
		while (($data = fgetcsv($handle, 1000, ",")) !== FALSE) {
			$num = count($data);
			$row++;
			if ($row > 1){
				for ($c=0; $c < $num; $c++) {
					if ($c == 10){
						$house = strpos($data[$c],'PA House');
						$city = strpos($data[$c],'Phila City Council');
						$cong = strpos($data[$c],'PA Congressional');
						$senate = strpos($data[$c],'PA Senatorial');

						// list of PA House districts
						if ($house !== false) {
							$house = explode(" ",$data[$c]);
							array_push($dis_house, end($house));
						}

						// list of CITY districts
						if ($city !== false) {
							$city = explode(" ",$data[$c]);
							array_push($dis_city, end($city));
						}

						// list of Congressional districts
						if ($cong !== false) {
							$cong = explode(" ",$data[$c]);
							array_push($dis_cong, end($cong));
						}

						// list of PA House districts
						if ($senate !== false) {
							$senate = explode(" ",$data[$c]);
							array_push($dis_senate, end($senate));
						}
					}
				}
			}
		}
		fclose($handle);
	}

	$house_list = '';
	$city_list = '';
	$cong_list = '';;
	$senate_list = '';
	
	foreach($dis_house as $house_item){
		$house_list .= $house_item.',';
	}
	$house_list = substr($house_list, 0, -1);


	foreach($dis_city as $city_item){
		$city_list .= $city_item.',';
	}
	$city_list = substr($city_list, 0, -1);

	foreach($dis_cong as $cong_item){
		$cong_list .= $cong_item.',';
	}
	$cong_list = substr($cong_list, 0, -1);	

	foreach($dis_senate as $senate_item){
		$senate_list .= $senate_item.',';
	}
	$senate_list = substr($senate_list, 0, -1);

	$insert = "INSERT INTO routes (rt_name, rt_desc, dis_city_council, dis_pa_house, dis_pa_senate, dis_pa_congress, ridership) VALUES ('".$route."','','".$city_list."','". $house_list."','". $senate_list."','". $cong_list."','"."');";

	echo $insert."\n";

}


?>
